### ISSUE TITLE
AddRelTag is not working.

### ISSUE THREAD

**Issue by kysee** [marcozaccari/markdown-diagrams-browser-extension#3]
I set the line color and text color by using AddRelTag.  
As you see in the following diagram, 
the color is not changed and the tags are not shown in the legend table.

```
@startuml
!include C4_Context.puml

AddRelTag(redtext, $textColor="red")
AddRelTag(redline, $lineColor="red")
AddRelTag(redtext&redline, $textColor="red", $lineColor="red")

Person(U, "User")
System(A, "A System", "Description for A System.")
System_Ext(B, "B System", "This is external systems.")
Rel(U, A, "Do somethings", $tags="redtext&redline+redtext+redline")
Rel(A, B, "Request somethings")

SHOW_LEGEND()
@enduml
```

**Comment by marcozaccari** [comment]
Hi, I've tried directly in Kroki live editor: https://kroki.io/#try
and it looks like their server has a slightly older version of C4.
(Kroki is the render provider used by default by Markdown Diagrams, look at the extension settings)

So the correct place to open this issue is https://github.com/yuzutech/kroki/issues

I just hope I've been of some help.
